window.projectsData = [
    {
        "id": "au-fil-de-l-eau",
        "title": "AU FIL<br>DE L'EAU",
        "titleEn": "OVER<br>THE WATER",
        "category": "Logement Tertiaire",
        "categoryEn": "Tertiary Housing",
        "location": "Saly, Sénégal",
        "locationEn": "Saly, Senegal",
        "year": "2025",
        "surface": "1000 m²",
        "programme": "Maison d'hôtes",
        "programmeEn": "Guest house",
        "mission": "Commande · Études programmatiques · Recherches architecturales · Recherche de matériaux · Développement du concept architectural · Visualisations 3D",
        "missionEn": "Direct commission · Programmatic studies · Architectural research · Material research · Architectural concept development · 3D Visualizations",
        "status": "Concours",
        "statusEn": "Competition",
        "description": "Au fil de l'eau imagine une maison contemporaine où l'architecture se construit autour de l'eau, de la lumière et de la nature. Le projet s'organise autour d'un bassin central qui accompagne les perspectives et les circulations, créant un cœur calme et contemplatif au sein de l'habitation.<br><br>Au centre de cette composition, une statuette inspirée de la Joconde devient un élément artistique majeur, établissant un dialogue entre l'art, l'architecture et le paysage. Ses reflets dans l'eau renforcent cette volonté de créer une architecture sensible, au-delà de la simple fonction.<br><br>L'écriture architecturale associe volumes épurés, grandes ouvertures vitrées et matériaux naturels et contemporains tels que la pierre, le bois, le béton et l'acier corten. Ce choix permet de conjuguer une esthétique chic, chaleureuse et intemporelle avec une approche plus responsable de la construction.<br><br>La lumière naturelle, la végétation et l'eau participent pleinement au confort des espaces, tandis que l'éclairage architectural prolonge l'expérience à la tombée du jour.<br><br>Au fil de l'eau propose ainsi une manière d'habiter où chaque espace devient une expérience, entre matière, lumière, art et nature.",
        "descriptionEn": "Over the water imagines a contemporary house where architecture is built around water, light and nature. The project is organized around a central pool that accompanies perspectives and circulations, creating a calm and contemplative heart within the home.<br><br>At the center of this composition, a statuette inspired by the Mona Lisa becomes a major artistic element, establishing a dialogue between art, architecture and landscape. Its reflections in the water reinforce this desire to create sensitive architecture, beyond simple function.<br><br>The architectural style combines clean volumes, large glass openings and natural, contemporary materials such as stone, wood, concrete and corten steel. This choice makes it possible to combine a chic, warm and timeless aesthetic with a more responsible approach to construction.<br><br>Natural light, vegetation and water participate fully in the comfort of the spaces, while architectural lighting prolongs the experience at nightfall.<br><br>Over the water thus offers a way of living where each space becomes an experience, between material, light, art and nature.",
        "image": "/images/projects/rendu cour 16h.png",
        "timeLapseImages": [
            "/images/projects/rendu cour 7h.png",
            "/images/projects/rendu cour 16h.png",
            "/images/projects/rendu cour soir 21h.png"
        ],
        "timeLabels": ["07h00", "16h00", "21h00"],
        "gallery": [
            { "src": "/images/projects/rendu cour 16h.png", "title": "Passage du Temps", "isTimeLapse": true },
            { "src": "/images/projects/Test Vue principale.png", "title": "Vue Principale" },
            { "src": "/images/projects/Test Rooftop.png", "title": "Rooftop" },
            { "src": "/images/projects/Test Vue du haut.png", "title": "Vue du Haut" },
            { "src": "/images/projects/05.png", "title": "Intérieur" }
        ]
    },
    {
        "id": "azuria",
        "title": "MAISON<br>AZURIA",
        "titleEn": "AZURIA<br>HOUSE",
        "category": "Logement Tertiaire",
        "categoryEn": "Tertiary Housing",
        "location": "Dakar, Sénégal",
        "locationEn": "Dakar, Senegal",
        "year": "2025 - 2026",
        "surface": "350 m²",
        "programme": "Maison moderne haut de gamme",
        "programmeEn": "High-end modern residence",
        "mission": "Études de faisabilité · Recherches architecturales · Recherche de matériaux · Développement du concept architectural · Aménagement intérieur · Aménagement extérieur · Visualisations 3D",
        "missionEn": "Feasibility studies · Architectural research · Material research · Architectural concept development · Interior design · Exterior landscape design · 3D Visualizations",
        "status": "Études de conception",
        "statusEn": "Design studies",
        "description": "La Maison Azuria propose une architecture contemporaine haut de gamme, pensée autour de la lumière, du confort et d'une relation étroite entre les espaces intérieurs et le jardin. Le projet s'organise autour d'un espace de vie généreusement ouvert sur l'extérieur, offrant une continuité visuelle fluide entre le séjour, la terrasse et le paysage.<br><br>Les façades associent des lignes épurées, de grandes baies vitrées et des claustras en bois noble, créant une architecture à la fois sobre, chaleureuse et intimement liée au climat de Dakar. À l'intérieur, le bois, les textures naturelles et un éclairage scénographique soigneusement intégré renforcent l'atmosphère élégante et accueillante de la résidence.<br><br>L'aménagement paysager prolonge harmonieusement les espaces de vie avec des terrasses en platelage bois, des plantations tropicales, une piscine linéaire et des cheminements en dalles minérales, faisant du jardin un véritable prolongement à ciel ouvert de l'habitation.",
        "descriptionEn": "Azuria House offers high-end contemporary architecture designed around light, comfort, and an intimate dialogue between interior spaces and the garden. The project is organized around a living space generously opened to the outside, providing a seamless visual continuity between the living room, the terrace, and the landscape.<br><br>The facades combine clean geometric lines, large glass panes, and refined wood louvers, creating an architecture that is simultaneously understated, warm, and tailored to Dakar's climate. Inside, wood craftsmanship, natural textures, and integrated architectural lighting enhance the residence's welcoming and sophisticated ambiance.<br><br>The landscape design seamlessly extends the living quarters with timber deck terraces, tropical vegetation, a lap pool, and stone pathways, making the garden a true open-air living extension of the home.",
        "image": "/images/projects/azuria-facade.png",
        "gallery": [
            { "src": "/images/projects/azuria-terrasse-piscine.png", "title": "Terrasse, Jardin & Piscine" },
            { "src": "/images/projects/azuria-jardin-sejour.png", "title": "Continuité Séjour & Extérieur" },
            { "src": "/images/projects/azuria-interieur.png", "title": "Espaces de Vie & Salon" }
        ]
    },
    {
        "id": "ecolodge-saint-louis",
        "title": "ÉCOLODGE<br>DE SAINT-LOUIS",
        "titleEn": "SAINT-LOUIS<br>ECOLODGE",
        "category": "Mixte / Équipement / Logements",
        "categoryEn": "Mixed-Use / Hospitality / Housing",
        "location": "Saint-Louis, Sénégal",
        "locationEn": "Saint-Louis, Senegal",
        "year": "2026",
        "surface": "2 hectares",
        "programme": "Écolodge touristique",
        "programmeEn": "Eco-tourism lodge resort",
        "mission": "Études de faisabilité · Études programmatiques · Recherches architecturales · Développement du concept architectural · Visualisations 3D · Dossier de conception",
        "missionEn": "Feasibility studies · Programmatic studies · Architectural research · Architectural concept development · 3D Visualizations · Design development documentation",
        "status": "Études de conception",
        "statusEn": "Design studies",
        "description": "Situé à Saint-Louis, au Sénégal, ce projet d'écolodge s'implante sur un vaste terrain de 2 hectares au cœur d'un paysage aride. Pensé comme une destination touristique d'exception, le complexe s'organise en plusieurs pôles d'hébergement afin de répondre aux différents profils de visiteurs tout en offrant une expérience immersive en lien avec la nature.<br><br>Notre intervention comprend les études de faisabilité, les études programmatiques, les recherches architecturales, le développement du concept architectural ainsi que l'élaboration complète du dossier de conception.<br><br>Le programme comprend des cases présidentielles bénéficiant chacune d'un jardin privatif et d'une piscine, un espace familial composé d'hébergements organisés autour d'une piscine dédiée aux enfants, ainsi que des cases traditionnelles disposant de jardins privatifs. Au cœur de l'écolodge, une grande piscine centrale constitue le principal lieu de rencontre et de détente. L'ensemble est complété par deux restaurants, un terrain de tennis, un cinéma en plein air, des salles polyvalentes et de vastes espaces paysagers favorisant les promenades et les activités de loisirs.<br><br>Le principal défi du projet consistait à structurer un programme de grande envergure sur un site aux conditions climatiques exigeantes, tout en garantissant l'intimité de chaque secteur. L'implantation des différents pôles a été pensée pour créer une hiérarchie claire des espaces, favoriser les circulations douces et offrir une intégration harmonieuse de l'architecture dans son environnement naturel.",
        "descriptionEn": "Located in Saint-Louis, Senegal, this eco-lodge project is set across a 2-hectare estate in the heart of an arid landscape. Designed as an exceptional eco-tourism destination, the complex is structured into multiple hospitality clusters to cater to diverse visitor profiles while delivering an immersive experience in close harmony with nature.<br><br>Our scope encompassed feasibility studies, programmatic definition, architectural research, architectural concept development, and full design development documentation.<br><br>The program features presidential lodges with private gardens and exclusive swimming pools, a family cluster organized around a dedicated children's pool, and traditional huts with secluded private gardens. At the heart of the lodge, a generous central pool serves as the main social and relaxation hub, complemented by two restaurants, tennis courts, an open-air cinema, multipurpose rooms, and vast landscaped open spaces for leisure and walking.<br><br>The primary design challenge was to structure a large-scale program on a climatically demanding site while safeguarding the privacy of each hospitality enclave. The master layout establishes a clear spatial hierarchy, fosters gentle circulations, and achieves a harmonious, bioclimatic integration within its natural surroundings.",
        "image": "/images/projects/ecolodge-stlouis-piscine-restaurant.png",
        "gallery": [
            { "src": "/images/projects/ecolodge-stlouis-piscine-restaurant.png", "title": "Écolodge de Saint-Louis" }
        ]
    },
    {
        "id": "keur-cheikh-sadieye",
        "title": "ENSEMBLE RÉSIDENTIEL ET CULTUEL<br>KEUR CHEIKH SADIEYE",
        "titleEn": "RESIDENTIAL AND SPIRITUAL COMPLEX<br>KEUR CHEIKH SADIEYE",
        "category": "Mixte / Logements / Équipement",
        "categoryEn": "Mixed-Use / Housing / Cultural & Religious Facility",
        "location": "Touba, Sénégal",
        "locationEn": "Touba, Senegal",
        "year": "2026",
        "surface": "1,5 hectare",
        "programme": "Ensemble résidentiel et cultuel · Logements · Mosquée",
        "programmeEn": "Residential and spiritual complex · Housing · Mosque",
        "mission": "Études de faisabilité · Études programmatiques · Recherches architecturales · Développement du concept architectural · Dossier de conception · Visualisations 3D",
        "missionEn": "Feasibility studies · Programmatic studies · Architectural research · Architectural concept development · Design development documentation · 3D Visualizations",
        "status": "Études de conception",
        "statusEn": "Design studies",
        "description": "Implanté au cœur de Touba, ville religieuse majeure du Sénégal, ce projet propose un ensemble résidentiel et cultuel pensé autour des valeurs de communauté, de spiritualité et de convivialité. Le programme associe des logements à une mosquée, organisée comme un espace de rassemblement et de vie collective.<br><br>Le projet recherche un équilibre entre architecture contemporaine et identité locale, à travers une composition sobre, des espaces extérieurs paysagers et une organisation favorisant les cheminements piétons et les rencontres. La disposition des bâtiments permet de créer des espaces communs adaptés aux usages quotidiens et aux temps de rassemblement.<br><br>L’aménagement du site accorde également une attention particulière à la végétation, aux espaces ombragés et à la qualité des parcours, afin de proposer un cadre de vie confortable et adapté au climat de Touba.",
        "descriptionEn": "Located in the heart of Touba, a major religious city in Senegal, this project introduces a residential and spiritual complex designed around the enduring values of community, spirituality, and shared living. The master program integrates residential quarters with a central mosque conceived as an open sanctuary for communal gathering and collective life.<br><br>The design strikes a deliberate harmony between contemporary architecture and local cultural identity through restrained compositions, landscaped outdoor courtyards, and a layout prioritizing pedestrian circulation and spontaneous encounters. The volumetric arrangement defines versatile public squares tailored for both daily routines and major communal assemblies.<br><br>The site planning places profound emphasis on indigenous landscaping, shaded colonnades, and contemplative pathways, ensuring thermal comfort and environmental resonance with Touba's climate.",
        "image": "/images/projects/keur-cheikh-sadieye-jour.png",
        "gallery": [
            { "src": "/images/projects/keur-cheikh-sadieye-jour.png", "title": "Cour Intérieure & Minaret (Jour)" },
            { "src": "/images/projects/keur-cheikh-sadieye-nuit.png", "title": "Atmosphère Nocturne & Dôme" },
            { "src": "/images/projects/keur-cheikh-sadieye-interieur.png", "title": "Salle de Prière & Lumière Zénithale" }
        ]
    },
    {
        "id": "immeuble-logements-services",
        "title": "IMMEUBLE DE LOGEMENTS<br>ET SERVICES",
        "titleEn": "HOUSING & SERVICES<br>BUILDING",
        "category": "Logement / Services",
        "categoryEn": "Housing & Services",
        "location": "Dakar, Sénégal",
        "locationEn": "Dakar, Senegal",
        "year": "2025 - 2026",
        "surface": "500 m²",
        "programme": "Immeuble de logements et services",
        "programmeEn": "Housing and local services building",
        "mission": "Études de faisabilité · Recherches architecturales · Recherche de matériaux · Développement du concept architectural · Aménagement intérieur et extérieur · Visualisations 3D",
        "missionEn": "Feasibility studies · Architectural research · Material research · Architectural concept development · Interior & exterior design · 3D Visualizations",
        "status": "Études de conception",
        "statusEn": "Design studies",
        "description": "Ce projet propose un immeuble contemporain de logements et de services, conçu comme un lieu de vie ouvert sur la ville. Le rez-de-chaussée accueille des commerces et services de proximité, tandis que les niveaux supérieurs sont dédiés aux logements, offrant aux habitants un cadre de vie confortable et lumineux.<br><br>L’architecture repose sur une façade structurée et largement végétalisée, où les balcons et terrasses deviennent de véritables extensions des logements. La présence de la végétation apporte fraîcheur et qualité d’usage tout en renforçant l’identité du bâtiment.<br><br>Le projet intègre également une approche durable et bioclimatique, avec une toiture végétalisée, des espaces paysagers et des panneaux photovoltaïques destinés à favoriser une meilleure performance énergétique. L’ensemble associe ainsi densité urbaine, confort résidentiel et respect de l’environnement.",
        "descriptionEn": "This project offers a contemporary mixed building of housing and services, designed as a living place open to the city. The ground floor hosts local shops and services, while the upper levels are dedicated to housing, offering residents a comfortable and luminous living environment.<br><br>The architecture relies on a structured and extensively vegetated facade, where balconies and terraces become true extensions of the apartments. The presence of vegetation brings freshness and quality of use while strengthening the building's identity.<br><br>The project also integrates a sustainable and bioclimatic approach, with a green roof, landscaped spaces and photovoltaic solar panels designed to promote better energy performance. The ensemble thus combines urban density, residential comfort and environmental respect.",
        "image": "/images/projects/immeuble-logements-services-facade.png",
        "gallery": [
            { "src": "/images/projects/immeuble-logements-services-facade.png", "title": "Façade Principale & Commerces RDC" },
            { "src": "/images/projects/immeuble-logements-services-rooftop.png", "title": "Toiture Végétalisée & Panneaux Solaires" },
            { "src": "/images/projects/immeuble-logements-services-sejour.png", "title": "Séjour & Terrasse Arborée" },
            { "src": "/images/projects/immeuble-logements-services-chambre.png", "title": "Chambre & Loggia Végétalisée" }
        ]
    },
    {
        "id": "pole-urbain-accueil-culture",
        "title": "PÔLE URBAIN D'ACCUEIL<br>ET DE CULTURE",
        "titleEn": "URBAN HOSTING & CULTURAL<br>CENTER",
        "category": "Mixte / Logements / Équipement / Bureaux",
        "categoryEn": "Mixed-Use / Housing / Cultural Facility / Offices",
        "location": "Toulouse, France (Projet académique)",
        "locationEn": "Toulouse, France (Academic project)",
        "year": "2024",
        "surface": "1500 m²",
        "programme": "Pôle d'hébergement et d'équipements culturels · Logements · Bureaux · Cinéma & Théâtre",
        "programmeEn": "Hosting and cultural facility center · Housing · Offices · Cinema & Theater",
        "mission": "Études de faisabilité · Études programmatiques · Recherches architecturales · Développement du concept architectural",
        "missionEn": "Feasibility studies · Programmatic studies · Architectural research · Architectural concept development",
        "status": "Projet académique",
        "statusEn": "Academic project",
        "description": "Développé dans le cadre d'un projet académique à Toulouse, ce projet propose la conception d'un immeuble contemporain réunissant un centre d'hébergement et d'accompagnement, des logements, des bureaux dédiés aux services sociaux ainsi que des équipements culturels ouverts au public. Pensé comme un véritable repère urbain, le bâtiment affirme son identité à travers une architecture largement vitrée, favorisant les échanges entre ses usagers et son environnement.<br><br>Notre démarche comprenait les études de faisabilité, les recherches architecturales, les études programmatiques ainsi que le développement du concept architectural.<br><br>Le rez-de-chaussée a été conçu comme un socle actif accueillant plusieurs restaurants, des salles d'exposition et un théâtre destiné à accueillir les programmations de la ville. À l'une des extrémités du projet, un vaste parvis ponctué d'emmarchements accompagne le dénivelé naturel du site et mène au cinéma, implanté au niveau inférieur (-1). Cette composition renforce la continuité entre l'espace public et les différents équipements, tout en créant un parcours architectural qui anime le bâtiment.<br><br>Les niveaux supérieurs accueillent les logements ainsi que les espaces d'hébergement et d'accompagnement dans une organisation privilégiant la lumière naturelle, le confort des occupants et la qualité des usages. L'utilisation du verre comme matériau principal confère à l'immeuble une identité contemporaine, tout en favorisant les transparences, les vues et le dialogue entre les espaces intérieurs et la ville.",
        "descriptionEn": "Developed as part of an academic project in Toulouse, this proposal introduces a contemporary mixed-use complex integrating a shelter and social support center, residential apartments, social service offices, and cultural venues open to the public. Envisioned as a civic landmark, the building asserts its presence through expansive glazing that fosters vibrant interactions between users and the urban setting.<br><br>The scope of work included feasibility studies, architectural research, programmatic development, and concept design.<br><br>The ground floor serves as an active civic plinth hosting dining venues, exhibition spaces, and a municipal theater. On the public square, stepped terraces navigate the natural site slope down to a subterranean cinema complex at level -1. This spatial sequencing establishes seamless continuity between the public realm and cultural amenities.<br><br>The upper volumes accommodate housing and social support programs organized to maximize natural daylighting, acoustic privacy, and occupant comfort. Glass curtain walling bestows a luminous, transparent identity while orchestrating open panoramas and dialogues with the city.",
        "image": "/images/projects/pole-urbain-toulouse.png",
        "gallery": [
            { "src": "/images/projects/pole-urbain-toulouse.png", "title": "Pôle Urbain d'Accueil et de Culture — Parvis & Cinéma" }
        ]
    },
    {
        "id": "ecole-primaire-kaira-looro",
        "title": "ÉCOLE PRIMAIRE<br>KAIRA LOORO",
        "titleEn": "KAIRA LOORO<br>PRIMARY SCHOOL",
        "category": "Concours / Équipement / Éducation",
        "categoryEn": "Competition / Public Facility / Education",
        "location": "Casamance, Sénégal",
        "locationEn": "Casamance, Senegal",
        "year": "2024 - 2025",
        "surface": "1 500 m²",
        "programme": "École primaire avec cantine · 5 salles de classe · Espaces administratifs · Cour à impluvium",
        "programmeEn": "Primary school with canteen · 5 classrooms · Administrative offices · Impluvium courtyard",
        "mission": "Concours · Études programmatiques · Recherches architecturales · Recherche de matériaux (BTC) · Développement du concept architectural · Visualisations 3D",
        "missionEn": "Competition · Programmatic studies · Architectural research · Material research (CEB) · Architectural concept development · 3D Visualizations",
        "status": "Concours",
        "statusEn": "Competition",
        "description": "Réalisé dans le cadre du concours international Kaira Looro, ce projet d'école primaire propose un équipement éducatif conçu pour répondre aux enjeux climatiques et environnementaux du territoire. Implanté sur une parcelle de 1 500 m², le programme comprend cinq salles de classe, une cantine et les espaces nécessaires au fonctionnement de l'établissement.<br><br>Notre démarche s'est inspirée des cases à impluvium, une typologie vernaculaire reconnue pour sa capacité à capter les eaux de pluie et à favoriser un confort climatique naturel. Cette référence a guidé la conception des espaces, l'organisation des bâtiments ainsi que le développement d'un système de récupération des eaux pluviales intégré au projet.<br><br>Le choix des blocs de terre comprimée (BTC) s'inscrit dans une volonté de privilégier des matériaux locaux à faible impact environnemental tout en assurant une bonne inertie thermique. Le principal défi consistait à développer un équipement scolaire fonctionnel et bioclimatique répondant à l'ensemble du programme dans une emprise limitée de 1 500 m², tout en offrant des espaces d'apprentissage confortables, durables et adaptés au climat local.",
        "descriptionEn": "Conceived as part of the Kaira Looro international competition, this primary school project delivers an educational facility deeply attuned to regional climatic and environmental realities. Set on a 1,500 m² footprint, the brief accommodates five classrooms, a community canteen, and essential administrative amenities.<br><br>Our approach drew inspiration from traditional impluvium huts, an ancestral Senegalese vernacular typology celebrated for passive rainwater harvesting and natural cooling. This heritage informed spatial organization, volumetric clustering, and an integrated rainwater catchment network.<br><br>The use of Compressed Earth Blocks (CEB / BTC) reflects a commitment to low-carbon, regionally sourced materials offering high thermal mass. The core ambition was delivering a functional, bioclimatic learning sanctuary within a constrained footprint, creating an enduring, healthy, and culturally grounded environment for children.",
        "image": "/images/projects/ecole-kaira-looro-exterieur.png",
        "gallery": [
            { "src": "/images/projects/ecole-kaira-looro-exterieur.png", "title": "Vue d'Ensemble & Rive du Fleuve" },
            { "src": "/images/projects/ecole-kaira-looro-cour.png", "title": "Cour Intérieure & Impluvium Ombragé" },
            { "src": "/images/projects/ecole-kaira-looro-classe.png", "title": "Salle de Classe & Moucharabiehs de Terre" }
        ]
    },
    {
        "id": "maison-23",
        "title": "MAISON 23",
        "titleEn": "HOUSE 23",
        "category": "Logement Tertiaire",
        "categoryEn": "Residential Housing",
        "location": "Dakar, Sénégal",
        "locationEn": "Dakar, Senegal",
        "year": "2025 - 2026",
        "surface": "160 m²",
        "programme": "Maison individuelle avec piscine · 3 chambres · Patio bioclimatique · Espace de vie ouvert",
        "programmeEn": "Single-family residence with swimming pool · 3 bedrooms · Bioclimatic patio · Open living area",
        "mission": "Conception des plans · Architecture d'intérieur · Visualisations 3D",
        "missionEn": "Floor plan design · Interior architecture · 3D Visualizations",
        "status": "Projet de conception",
        "statusEn": "Design project",
        "descriptionEn": "Designed for a client based in Spain looking to build a private residence in Dakar, this home accommodates three bedrooms, a swimming pool, and fluid living areas on an exceptionally narrow urban plot.<br><br>Our scope encompassed floor plan development, interior architecture, and 3D architectural visualizations. The primary challenge was maximizing every square meter while providing superior comfort and well-being. A lateral patio connecting the ground-floor bedroom and kitchen was introduced to invite cross-ventilation and natural daylight. At the front of the plot, a landscaped garden with a swimming pool extends the indoor living areas outdoors despite the tight parcel constraints.<br><br>The photorealistic 3D visualisations empowered the client to vividly experience their future home and finalize architectural and bespoke interior choices ahead of construction.",
        "image": "/images/projects/maison-23-facade.png",
        "gallery": [
            { "src": "/images/projects/maison-23-facade.png", "title": "Façade Principale & Clôture Minérale" },
            { "src": "/images/projects/maison-23-sejour-piscine.png", "title": "Séjour Contemporain & Terrasse Piscine" }
        ]
    },
    {
        "id": "maison-mandy",
        "title": "MAISON MANDY",
        "titleEn": "MANDY HOUSE",
        "category": "Logement Tertiaire",
        "categoryEn": "Residential Housing",
        "location": "Gabon",
        "locationEn": "Gabon",
        "year": "2023 - 2024",
        "surface": "400 m²",
        "programme": "Maison familiale haut de gamme · Espaces de vie ouverts · Suite parentale · Pergola paysagère & Carport",
        "programmeEn": "High-end family villa · Open living spaces · Master suite · Landscaped pergola & Carport",
        "mission": "Études de faisabilité · Recherches architecturales · Recherche de matériaux · Développement du concept architectural · Aménagement intérieur et extérieur · Visualisations 3D",
        "missionEn": "Feasibility studies · Architectural research · Material research · Architectural concept development · Interior & exterior design · 3D Visualizations",
        "status": "Études de conception",
        "statusEn": "Design studies",
        "description": "Cette maison familiale haut de gamme propose une architecture contemporaine, élégante et chaleureuse, pensée autour du confort, de la lumière naturelle et de la relation avec le paysage. Le rez-de-chaussée accueille les principaux espaces de vie, tandis que l’étage regroupe les chambres et les espaces privés.<br><br>L’architecture se caractérise par des volumes épurés et de larges ouvertures vitrées, favorisant la lumière et les perspectives vers les espaces extérieurs. La pierre et le bois sont privilégiés pour leur aspect naturel et chaleureux, créant un contraste harmonieux avec les lignes sobres et modernes de la façade.<br><br>Les aménagements extérieurs prolongent les espaces de vie et renforcent la continuité entre architecture, jardin et environnement.",
        "descriptionEn": "This high-end family residence offers a contemporary, elegant and warm architecture, designed around comfort, natural light, and an intimate connection with the landscape. The ground floor accommodates the primary open-plan living areas, while the upper level hosts private suites and bedrooms.<br><br>The architectural expression is defined by pure volumetric forms and extensive floor-to-ceiling glazing, maximizing daylighting and offering expansive views toward the garden. Natural stone masonry and warm timber screens are thoughtfully paired to contrast with the crisp, modern lines of the white rendered facade.<br><br>Landscaped outdoor spaces seamlessly extend the interior rooms, reinforcing the fluid continuity between architecture, lush gardens, and the natural surroundings.",
        "image": "/images/projects/maison-mandy-facade.png",
        "gallery": [
            { "src": "/images/projects/maison-mandy-facade.png", "title": "Façade Principale & Pergola Paysagère" }
        ]
    },
    {
        "id": "maison-obsidienne",
        "title": "MAISON OBSIDIENNE",
        "titleEn": "OBSIDIAN HOUSE",
        "category": "Logement Tertiaire",
        "categoryEn": "Residential Housing",
        "location": "Kigali, Rwanda",
        "locationEn": "Kigali, Rwanda",
        "year": "2024",
        "surface": "150 m²",
        "programme": "Maison individuelle haut de gamme · Architecture minérale · Espaces de vie ouverts · Brise-soleil intégrés",
        "programmeEn": "High-end single-family residence · Mineral architecture · Open living spaces · Integrated sunshades",
        "mission": "Études de faisabilité · Recherches architecturales · Recherche de matériaux · Développement du concept architectural",
        "missionEn": "Feasibility studies · Architectural research · Material research · Architectural concept development",
        "status": "Études de conception",
        "statusEn": "Design studies",
        "description": "Conçue pour un entrepreneur souhaitant une résidence contemporaine, masculine et haut de gamme, cette maison développe une écriture architecturale sobre et affirmée, où la matérialité et les volumes expriment une identité forte.<br><br>Notre intervention comprenait les études de faisabilité, les recherches architecturales, la sélection des matériaux et le développement du concept architectural.<br><br>L'un des principes fondateurs du projet réside dans la dualité entre les deux façades. Côté rue, la maison se présente comme un volume minéral aux teintes grises et noires, volontairement fermé et protecteur. Les ouvertures sont limitées afin de préserver l'intimité des occupants et de renforcer le caractère monolithique de l'ensemble. Cette façade affirme une présence sobre, puissante et énigmatique.<br><br>À l'inverse, la façade tournée vers le jardin s'ouvre largement sur les espaces extérieurs grâce à de généreuses baies vitrées. Cette transition révèle une architecture plus lumineuse et conviviale, où les pièces de vie prolongent naturellement les terrasses et le paysage. Le travail de recherche sur les matériaux a permis de concilier élégance, durabilité et cohérence esthétique, afin de traduire les attentes du client à travers une architecture de caractère.",
        "descriptionEn": "Designed for an entrepreneur envisioning a contemporary, masculine, and sophisticated residence, this home develops a restrained yet assertive architectural vernacular where materiality and volumetric clarity express a powerful identity.<br><br>Our scope of work encompassed feasibility studies, architectural research, materials curation, and concept development.<br><br>A fundamental principle of the design lies in the intentional duality between the two facades. On the street side, the house presents itself as a dark mineral monolithic volume in deep grey and black tones, deliberately enclosed and protective. Fenestration is strictly measured to safeguard privacy and amplify the monolithic sculptural presence.<br><br>Conversely, the garden-facing elevation opens expansively to the exterior realm via generous floor-to-ceiling glass assemblies. This transition reveals a luminous, convivial sanctuary where interior living suites naturally spill onto terraces and the surrounding landscape.",
        "image": "/images/projects/maison-obsidienne-facade-nuit.png",
        "gallery": [
            { "src": "/images/projects/maison-obsidienne-facade-nuit.png", "title": "Façade Monolithique & Atmosphère Nocturne" }
        ]
    },
    {
        "id": "maison-rehabilitation-magasin",
        "title": "MAISON RÉHABILITATION<br>AVEC MAGASIN",
        "titleEn": "HOUSE REHABILITATION<br>WITH RETAIL SPACE",
        "category": "Logement Tertiaire / Restructuration",
        "categoryEn": "Residential Housing / Adaptive Reuse",
        "location": "Dakar, Sénégal",
        "locationEn": "Dakar, Senegal",
        "year": "2025",
        "surface": "200 m²",
        "programme": "Réhabilitation d'une maison avec magasin · Patios intérieurs · Séjour décloisonné · Salle à manger",
        "programmeEn": "House rehabilitation with retail boutique · Internal patios · Open living area · Dining lounge",
        "mission": "Réhabilitation · Aménagement intérieur · Visualisations 3D",
        "missionEn": "Rehabilitation · Interior design · 3D Visualizations",
        "status": "Projet de conception",
        "statusEn": "Design project",
        "description": "Ce projet de réhabilitation porte sur une maison de 200 m² comprenant également un espace commercial. L'intervention visait à repenser entièrement l'organisation intérieure d'un bâtiment existant dont la configuration présentait de nombreuses contraintes, notamment des murs irréguliers et une implantation peu adaptée aux usages contemporains.<br><br>Le principal défi consistait à composer avec cette structure existante tout en améliorant le confort et la qualité des espaces. Afin de répondre aux besoins de ventilation et d'éclairage naturel des pièces d'eau, une série de patios a été intégrée entre les salles de bains. Ces vides deviennent de véritables respirations au cœur du projet, favorisant une aération naturelle efficace tout en apportant de la lumière aux espaces les plus enclavés.<br><br>La réorganisation des volumes a permis de créer une habitation plus fonctionnelle, plus fluide et mieux adaptée aux usages quotidiens, tout en intégrant harmonieusement le magasin au rez-de-chaussée. Les visualisations 3D ont accompagné cette réflexion en offrant une lecture claire des nouvelles intentions architecturales et en permettant au client de se projeter dans la transformation du bâtiment.",
        "descriptionEn": "This rehabilitation project involves a 200 m² residence integrating a street-level commercial boutique. The architectural intervention focused on entirely rethinking the interior spatial organization of an existing structure characterized by irregular masonry alignments and an outdated floor plan unsuited to contemporary living.<br><br>The primary challenge was transforming the existing structural envelope while drastically enhancing daylighting and spatial comfort. To ensure optimal natural cross-ventilation and daylight for the wet areas, a series of micro-patios was integrated between the bathrooms. These pocket courtyards act as vital breathing organs at the heart of the home, drawing daylight into deep spaces while ensuring passive thermal comfort.<br><br>The volumetric reorganization created a fluid, highly functional residence harmoniously paired with the ground-floor retail space. Photorealistic 3D visualisations guided the client throughout the transformation journey.",
        "image": "/images/projects/maison-rehab-magasin-facade.png",
        "gallery": [
            { "src": "/images/projects/maison-rehab-magasin-facade.png", "title": "Façade Sur Rue & Magasin RDC" },
            { "src": "/images/projects/maison-rehab-magasin-sejour-tv.png", "title": "Séjour Décloisonné & Espace TV" },
            { "src": "/images/projects/maison-rehab-magasin-sejour-salon.png", "title": "Salon & Puits de Lumière" }
        ]
    },
    {
        "id": "maison-terra",
        "title": "MAISON TERRA",
        "titleEn": "TERRA HOUSE",
        "category": "Logement Tertiaire",
        "categoryEn": "Residential Housing",
        "location": "Dakar, Sénégal",
        "locationEn": "Dakar, Senegal",
        "year": "2023 - 2024",
        "surface": "250 m²",
        "programme": "Maison familiale bioclimatique · Construction en BTC · Écosystème paysager & Bassin · Accessibilité universelle",
        "programmeEn": "Bioclimatic family residence · CEB earth construction · Landscaped garden & pond · Universal accessibility",
        "mission": "Études de faisabilité · Recherches architecturales · Recherche de matériaux · Développement du concept architectural · Aménagement intérieur et extérieur · Visualisations 3D",
        "missionEn": "Feasibility studies · Architectural research · Material research · Architectural concept development · Interior & exterior design · 3D Visualizations",
        "status": "Études de conception",
        "statusEn": "Design studies",
        "description": "Conçue pour une cliente souhaitant une maison familiale bioclimatique alliant confort, accessibilité et intégration paysagère, cette résidence en blocs de terre comprimée (BTC) développe une architecture inspirée des matériaux naturels et des savoir-faire locaux. Le projet intègre un écosystème paysager composé d'un jardin généreusement végétalisé et d'un bassin, participant à la qualité des espaces extérieurs et au confort du cadre de vie.<br><br>Notre intervention comprenait les études de faisabilité, les recherches architecturales, la recherche de matériaux ainsi que le développement du concept architectural. Le principal défi consistait à concevoir une habitation entièrement accessible, tout en préservant la qualité architecturale du projet. L'organisation des espaces, les circulations et les aménagements ont ainsi été pensés pour garantir une utilisation fluide, confortable et inclusive.<br><br>Une attention particulière a également été portée à la cohérence entre les espaces intérieurs et extérieurs. Le choix des matériaux, notamment les blocs de terre comprimée (BTC) et les parements en bois, ainsi que le traitement paysager, participent à créer une continuité naturelle entre l'architecture et son environnement. Cette approche confère à la maison une identité chaleureuse, inspirée d'une esthétique rustique réinterprétée dans une écriture contemporaine.",
        "descriptionEn": "Designed for a client seeking a bioclimatic family residence combining comfort, universal accessibility, and landscape integration, this home constructed with Compressed Earth Blocks (CEB / BTC) develops an architectural expression rooted in natural materials and local craftsmanship. The project incorporates a lush landscape ecosystem with generous greenery and a water basin, elevating outdoor comfort and daily well-being.<br><br>Our scope encompassed feasibility studies, architectural research, materials curation, and concept development. The primary ambition was creating an entirely accessible dwelling while preserving strong architectural character and refined aesthetics. Spatial layout, circulation axes, and interior fixtures are organized to ensure seamless, inclusive flow throughout.<br><br>Particular care was dedicated to bridging interior and exterior living. Compressed earth block masonry, natural wood accents, and lush plantings forge a harmonious dialogue between the built form and its setting, giving the home a warm, grounded identity where rustic vernacular meets contemporary finesse.",
        "image": "/images/projects/maison-terra-facade-nuit.png",
        "gallery": [
            { "src": "/images/projects/maison-terra-facade-nuit.png", "title": "Façade Bioclimatique en BTC & Jardin Paysager" }
        ]
    },
    {
        "id": "primary-school-senegal",
        "title": "PRIMARY SCHOOL<br>SENEGAL",
        "titleEn": "PRIMARY SCHOOL<br>SENEGAL",
        "category": "Concours / Équipement / Éducation",
        "categoryEn": "Competition / Public Facility / Education",
        "location": "Sénégal",
        "locationEn": "Senegal",
        "year": "2025",
        "surface": "2 500 m²",
        "programme": "École primaire avec cantine · Ateliers pratiques · Cour centrale paysagère · Pavillons modulaires",
        "programmeEn": "Primary school with canteen · Hands-on workshops · Landscaped central playground · Modular pavilions",
        "mission": "Concours · Études programmatiques · Recherches architecturales · Recherche de matériaux · Développement du concept architectural · Visualisations 3D",
        "missionEn": "Competition · Programmatic studies · Architectural research · Material research · Architectural concept development · 3D Visualizations",
        "status": "Concours · Concepteurs : Fadel Mbaye, Oledje Agbo, Remi Duhau",
        "statusEn": "Competition · Designers: Fadel Mbaye, Oledje Agbo, Remi Duhau",
        "description": "<strong>Une École Expérimentale</strong><br>Cette école est conçue comme un lieu où l'apprentissage dépasse le cadre académique traditionnel. Elle fonctionne comme un laboratoire vivant où les élèves allient connaissances théoriques et expérimentation pratique. Des espaces d'ateliers dédiés permettent aux élèves de manipuler directement les matériaux, d'explorer les formes, les couleurs et les techniques constructives. L'architecture elle-même participe au processus d'apprentissage en stimulant la curiosité, la créativité et la compréhension de la matière. Ce concept de laboratoire dépasse les limites physiques de l'école : les élèves y développent des compétences qui leur permettront plus tard de contribuer à la construction d'autres écoles et d'équipements communautaires, favorisant le transfert de savoir-faire, l'emploi local et l'autonomie régionale.<br><br><strong>Matériaux Locaux et Savoir-Faire Artisanal</strong><br>Le projet est principalement édifié en briques de terre comprimée (BTC) produites sur place à l'aide de presses manuelles, valorisant l'argile locale abondante au Sénégal. Cette mise en œuvre garantit une grande efficacité constructive, une durabilité exemplaire et une faible empreinte carbone tout en affirmant une forte identité locale. Des colonnes métalliques fines soutiennent des pergolas ombragées, tandis que le typha est utilisé en toiture légère et la canne à sucre locale pour les menuiseries des portes et fenêtres.<br><br><strong>Modularité Architecturale et Réponse Climatique</strong><br>L'école s'articule en volumes modulaires organisés autour d'une cour de récréation centrale et d'arbres existants soigneusement préservés. Les ouvertures cintrées, inspirées de l'architecture sénégalaise traditionnelle, assurent un contrôle solaire optimal et une excellente ventilation traversante. Le tissage ajouré des briques en façade agit comme un moucharabieh bioclimatique filtrant la lumière directe et créant des jeux d'ombres dynamiques sans recours à la climatisation mécanique.<br><br><strong>Toiture et Gestion des Eaux Pluviales</strong><br>Le système de toiture prolonge la géométrie modulaire en briques de terre. Ses pans inclinés assurent une évacuation et une collecte efficaces des eaux de pluie lors des saisons pluvieuses, renforçant la résilience écologique de l'ensemble.",
        "descriptionEn": "<strong>An Experimental School</strong><br>This school is conceived as a place where learning extends beyond conventional academic education. It functions as a living laboratory, where students combine theoretical knowledge with hands-on experimentation. Dedicated workshop spaces allow students to work directly with materials, testing shapes, colors, and construction techniques. The architecture itself becomes part of the learning process, encouraging curiosity, creativity, and material understanding. Students acquire skills that enable them to later participate in building other schools and community facilities, supporting long-term knowledge transfer, local employment opportunities, and regional self-sufficiency.<br><br><strong>Local Materials and Craftsmanship</strong><br>The project is constructed primarily from locally sourced clay bricks, a material widely available in Senegal. Bricks are handmade on site using a manual compressed earth block (CEB) press, ensuring consistent modular dimensions, high thermal inertia, and minimal environmental impact. Iron columns are used for shading pergolas, while typha cattail forms a lightweight roofing layer and local sugarcane is woven into door and window shutters.<br><br><strong>Architectural Modularity and Climate Response</strong><br>The school is composed of modular pavilions clustered around a central playground and preserved shade trees. Arched openings inspired by vernacular Senegalese forms ensure controlled daylighting and passive cross-ventilation. Porous brick screening filters intense sunlight, mitigating glare and fostering natural air currents without mechanical cooling.<br><br><strong>Roof and Rainwater Management</strong><br>The sloped roofscape extends the earth brick vernacular to optimize seasonal rainwater harvesting and gravity drainage, reinforcing a robust climate-resilient framework.",
        "image": "/images/projects/primary-school-cour-generale.png",
        "gallery": [
            { "src": "/images/projects/primary-school-cour-generale.png", "title": "Cour Centrale Arborée & Pavillons Modulaires" },
            { "src": "/images/projects/primary-school-entree-arcades.png", "title": "Portique d'Entrée & Moucharabiehs de Briques" },
            { "src": "/images/projects/primary-school-cour-arche.png", "title": "Cadrage sous Arche & Allée Principale" },
            { "src": "/images/projects/primary-school-classe-terre.png", "title": "Salle de Classe Voûtée en Terre & Mobilier" }
        ]
    },
    {
        "id": "restaurant-guiberoua",
        "title": "RESTAURANT GUIBÉROUA",
        "titleEn": "GUIBEROUA RESTAURANT",
        "category": "Mixte / Équipement / Logements",
        "categoryEn": "Mixed-use / Hospitality / Housing",
        "location": "Guibéroua, Côte d'Ivoire",
        "locationEn": "Guiberoua, Ivory Coast",
        "year": "2026",
        "surface": "500 m²",
        "programme": "Restaurant · Logements · Piscine · Aménagements paysagers & Espace lounge",
        "programmeEn": "Restaurant · Guest lodges · Swimming pool · Landscaped grounds & Lounge bar",
        "mission": "Conception architecturale · Recherches architecturales · Aménagement intérieur et extérieur · Développement du concept · Visualisations 3D",
        "missionEn": "Architectural design · Architectural research · Interior & exterior layout · Concept development · 3D Visualizations",
        "status": "Études de conception",
        "statusEn": "Design studies",
        "description": "Implanté à Guibéroua, en Côte d’Ivoire, ce projet propose un lieu de restauration et de détente conçu comme un espace ouvert sur son environnement naturel. Le programme associe un restaurant, des logements et une piscine, offrant une expérience complète entre convivialité, confort et déconnexion.<br><br>L’architecture privilégie une atmosphère chaleureuse et authentique, inspirée de l’artisanat et de l’identité culturelle locale. Le bois, le rotin et les matériaux naturels sont largement utilisés dans les espaces intérieurs, tandis que les grandes ouvertures favorisent la lumière naturelle et créent une continuité entre la salle et le jardin.<br><br>Les espaces extérieurs paysagers, associés à la piscine, prolongent les espaces de vie et créent différents lieux de détente. L’ensemble recherche une architecture sobre et contemporaine, en dialogue avec le climat et la végétation de la région de Guibéroua.",
        "descriptionEn": "Located in Guiberoua, Ivory Coast, this hospitality project creates a dining and relaxation sanctuary designed in direct dialogue with its lush natural surroundings. The master plan combines a gourmet restaurant, private guest lodges, and a swimming pool, offering an immersive experience of conviviality, comfort, and restorative escape.<br><br>The architecture cultivates a warm, authentic ambiance deeply inspired by Ivorian craftsmanship and cultural heritage. Solid timber, woven rattan, and natural tactile textures are prominently featured throughout the dining hall, while generous glazed openings invite abundant daylight and establish seamless fluidity between the interior salon and the surrounding tropical garden.<br><br>Landscaped outdoor terraces and the pool area extend the living spaces into diverse chill-out pockets, embodying a contemporary, restrained architectural vision attuned to the regional climate.",
        "image": "/images/projects/restaurant-guiberoua-salle.png",
        "gallery": [
            { "src": "/images/projects/restaurant-guiberoua-salle.png", "title": "Salle de Restaurant & Terrasse Végétalisée" }
        ]
    },
    {
        "id": "salle-des-fetes-guiberoua",
        "title": "SALLE DES FÊTES AVEC GUINGUETTE<br>ET ESPACES ADMINISTRATIFS",
        "titleEn": "EVENT HALL WITH GUINGUETTE<br>& ADMINISTRATIVE OFFICES",
        "category": "Équipement / Culture",
        "categoryEn": "Public Facility / Culture",
        "location": "Côte d'Ivoire – Projet confidentiel",
        "locationEn": "Ivory Coast – Confidential project",
        "year": "2025 - 2026",
        "surface": "1 600 m²",
        "programme": "Salles de réception · Scène & Cuisine professionnelle · Guinguette centrale · Bureaux administratifs",
        "programmeEn": "Reception halls · Stage & Commercial kitchen · Central courtyard guinguette · Administrative offices",
        "mission": "Études de faisabilité · Recherches architecturales · Recherche de matériaux · Dossier de conception",
        "missionEn": "Feasibility studies · Architectural research · Material research · Concept design package",
        "status": "Études de conception",
        "statusEn": "Design studies",
        "description": "Première salle des fêtes de ce village en Côte d'Ivoire, ce projet a été imaginé comme un équipement de référence destiné à accueillir mariages, cérémonies, événements culturels et rencontres communautaires. Le programme comprend plusieurs salles de réception, une scène, une cuisine professionnelle, une guinguette centrale ainsi que des bureaux administratifs.<br><br>Notre intervention comprenait les études de faisabilité, les recherches architecturales et techniques, la recherche de matériaux, ainsi que l'élaboration d'un dossier de conception destiné à accompagner le développement du projet et la recherche de financements.<br><br>Le principal défi consistait à organiser l'ensemble des espaces autour d'un patio central accueillant la guinguette. Véritable cœur du projet, ce patio structure les circulations, favorise les échanges entre les différents espaces et assure une ventilation naturelle des salles, offrant ainsi un meilleur confort thermique dans un climat chaud.<br><br>Le projet a également nécessité une réflexion approfondie sur le choix des matériaux. Le souhait du client d'intégrer de larges surfaces vitrées devait être concilié avec les contraintes climatiques locales. Une recherche spécifique a ainsi été menée afin d'identifier des solutions constructives adaptées au contexte, conciliant confort thermique, durabilité et qualité architecturale.<br><br>L'ensemble de ces études a permis de constituer un dossier de conception solide, offrant au client un support technique et architectural cohérent pour présenter son projet à de futurs partenaires financiers et préparer les prochaines phases de développement.",
        "descriptionEn": "As the first dedicated event hall in this village in Ivory Coast, this milestone project was conceived as a premier cultural and civic venue designed to host weddings, ceremonies, cultural performances, and community celebrations. The extensive brief accommodates multiple reception banquet halls, a scenic performance stage, a commercial catering kitchen, a central festive open-air guinguette, and administrative management offices.<br><br>Our scope of work encompassed feasibility studies, architectural and environmental research, material curation, and the production of a comprehensive concept design package intended to support project advancement and investor fundraising.<br><br>A defining design challenge was orchestrating the spatial circulation around a vibrant central patio housing the guinguette. Serving as the beating heart of the facility, this courtyard streamlines visitor movement, sparks social interaction, and establishes passive cross-ventilation across reception halls.<br><br>Material selection reconciled the client's desire for expansive glazed panoramas with regional tropical climate realities, deploying high-performance shading and durable local textures.",
        "image": "/images/projects/salle-des-fetes-guiberoua-facade.png",
        "gallery": [
            { "src": "/images/projects/salle-des-fetes-guiberoua-facade.png", "title": "Façade Principale & Rooftop Guinguette au Crépuscule" },
            { "src": "/images/projects/salle-des-fetes-guiberoua-reception.png", "title": "Grande Salle de Réception & Soirée de Gala" }
        ]
    }
];
